version: '3'

services:
    swoft:
       image: swoft/swoft:latest
       links:
         - mysql:mysql
#       build: ./
       ports:
         - "90:80"
         - "92:82"
         - "93:83"
       volumes:
         - ./:/var/www/swoft
         - /data/app/:/data/
         - /var/spool/cron/:/var/spool/cron/   #cron任务文件映射
       stdin_open: true
       tty: true
       privileged: true
#      容器启动时执行指令
       entrypoint: ["php", "/var/www/swoft/bin/swoft", "start"]
    mysql:
      image:  mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - /data/conf/mysql/conf:/etc/mysql/conf.d
        - /data/conf/mysql/data:/var/lib/mysql
      environment:
            MYSQL_ROOT_PASSWORD: 123456